packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
overrides:
  js-yaml: '>=5.2.2'
